const techIconMap: Record<string, string> = {
  Java: 'java-icon',
  'Java 17': 'java-icon',
  'Spring Boot': 'springboot-icon',
  'Node.js': 'nodedotjs-icon',
  'Express.js': 'express-icon',
  MongoDB: 'mongodb-icon',
  PostgreSQL: 'postgresql-icon',
  AWS: 'amazonaws-icon',
  Docker: 'docker-icon',
  'GitHub Actions': 'githubactions-icon',
  Nginx: 'nginx-icon',
  PM2: 'pm2-icon',
  RabbitMQ: 'rabbitmq-icon',
  JWT: 'jsonwebtokens-icon',
  React: 'react-icon',
  'React Native': 'react-icon',
  JavaScript: 'javascript-icon',
  TypeScript: 'typescript-icon',
  'Gemini API': 'googlegemini-icon',
  'Socket.IO': 'socketdotio-icon',
  Keycloak: 'keycloak-icon',
  Python: 'python-icon',
  'Cloudflare Workers': 'cloudflareworkers-icon',
  D1: 'cloudflare-icon',
  R2: 'cloudflare-icon',
  Hono: 'hono-icon',
  Zod: 'zod-icon',
  'React Router': 'reactrouter-icon',
  'Tailwind CSS': 'tailwindcss-icon',
  JUnit: 'junit5-icon',
  'JUnit 5': 'junit5-icon',
  Mockito: 'check-icon',

  Microservices: 'layers-icon',
  'Polyglot Persistence': 'layers-icon',
  'Event-Driven Architecture': 'layers-icon',
  'System Design': 'layers-icon',

  'REST APIs': 'api-icon',
  'API Orchestration': 'api-icon',
  'Backend APIs': 'api-icon',

  Caching: 'bolt-icon',
  'CI/CD': 'cicd-icon',
  Testing: 'check-icon',
  'Responsive UI': 'responsive-icon',
  Accessibility: 'accessibility-icon',
  OAuth2: 'lock-icon',

  'LLM Integration': 'sparkle-icon',
  'Recommendation Flows': 'sparkle-icon',
  'Prompt Design': 'sparkle-icon',
  'Prompt Workflows': 'sparkle-icon',
  'Evaluation Thinking': 'sparkle-icon',
}

export function getTechIconId(label: string): string | undefined {
  return techIconMap[label]
}
